# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nncv/Projects/cmakeSetup

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nncv/Projects/cmakeSetup

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nncv/Projects/cmakeSetup/CMakeFiles /home/nncv/Projects/cmakeSetup//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nncv/Projects/cmakeSetup/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/nncv/Projects/cmakeSetup/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mygame

# Build rule for target.
mygame: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mygame
.PHONY : mygame

# fast build rule for target.
mygame/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygame.dir/build.make CMakeFiles/mygame.dir/build
.PHONY : mygame/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty/glfw-3.3.2/src/CMakeFiles/glfw.dir/build.make thirdparty/glfw-3.3.2/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty/glad/CMakeFiles/glad.dir/build.make thirdparty/glad/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named stb_image

# Build rule for target.
stb_image: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stb_image
.PHONY : stb_image

# fast build rule for target.
stb_image/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty/stb_image/CMakeFiles/stb_image.dir/build.make thirdparty/stb_image/CMakeFiles/stb_image.dir/build
.PHONY : stb_image/fast

#=============================================================================
# Target rules for targets named stb_truetype

# Build rule for target.
stb_truetype: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stb_truetype
.PHONY : stb_truetype

# fast build rule for target.
stb_truetype/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty/stb_truetype/CMakeFiles/stb_truetype.dir/build.make thirdparty/stb_truetype/CMakeFiles/stb_truetype.dir/build
.PHONY : stb_truetype/fast

#=============================================================================
# Target rules for targets named raudio

# Build rule for target.
raudio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raudio
.PHONY : raudio

# fast build rule for target.
raudio/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty/raudio/CMakeFiles/raudio.dir/build.make thirdparty/raudio/CMakeFiles/raudio.dir/build
.PHONY : raudio/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty/imgui-docking/CMakeFiles/imgui.dir/build.make thirdparty/imgui-docking/CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named safeSave

# Build rule for target.
safeSave: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 safeSave
.PHONY : safeSave

# fast build rule for target.
safeSave/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty/safeSave/CMakeFiles/safeSave.dir/build.make thirdparty/safeSave/CMakeFiles/safeSave.dir/build
.PHONY : safeSave/fast

#=============================================================================
# Target rules for targets named gl2d

# Build rule for target.
gl2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gl2d
.PHONY : gl2d

# fast build rule for target.
gl2d/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty/gl2d/CMakeFiles/gl2d.dir/build.make thirdparty/gl2d/CMakeFiles/gl2d.dir/build
.PHONY : gl2d/fast

#=============================================================================
# Target rules for targets named glui

# Build rule for target.
glui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glui
.PHONY : glui

# fast build rule for target.
glui/fast:
	$(MAKE) $(MAKESILENT) -f thirdparty/glui/CMakeFiles/glui.dir/build.make thirdparty/glui/CMakeFiles/glui.dir/build
.PHONY : glui/fast

src/gameLayer/gameLayer.o: src/gameLayer/gameLayer.cpp.o
.PHONY : src/gameLayer/gameLayer.o

# target to build an object file
src/gameLayer/gameLayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygame.dir/build.make CMakeFiles/mygame.dir/src/gameLayer/gameLayer.cpp.o
.PHONY : src/gameLayer/gameLayer.cpp.o

src/gameLayer/gameLayer.i: src/gameLayer/gameLayer.cpp.i
.PHONY : src/gameLayer/gameLayer.i

# target to preprocess a source file
src/gameLayer/gameLayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygame.dir/build.make CMakeFiles/mygame.dir/src/gameLayer/gameLayer.cpp.i
.PHONY : src/gameLayer/gameLayer.cpp.i

src/gameLayer/gameLayer.s: src/gameLayer/gameLayer.cpp.s
.PHONY : src/gameLayer/gameLayer.s

# target to generate assembly for a file
src/gameLayer/gameLayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygame.dir/build.make CMakeFiles/mygame.dir/src/gameLayer/gameLayer.cpp.s
.PHONY : src/gameLayer/gameLayer.cpp.s

src/platform/glfwMain.o: src/platform/glfwMain.cpp.o
.PHONY : src/platform/glfwMain.o

# target to build an object file
src/platform/glfwMain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygame.dir/build.make CMakeFiles/mygame.dir/src/platform/glfwMain.cpp.o
.PHONY : src/platform/glfwMain.cpp.o

src/platform/glfwMain.i: src/platform/glfwMain.cpp.i
.PHONY : src/platform/glfwMain.i

# target to preprocess a source file
src/platform/glfwMain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygame.dir/build.make CMakeFiles/mygame.dir/src/platform/glfwMain.cpp.i
.PHONY : src/platform/glfwMain.cpp.i

src/platform/glfwMain.s: src/platform/glfwMain.cpp.s
.PHONY : src/platform/glfwMain.s

# target to generate assembly for a file
src/platform/glfwMain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygame.dir/build.make CMakeFiles/mygame.dir/src/platform/glfwMain.cpp.s
.PHONY : src/platform/glfwMain.cpp.s

src/platform/headerOnly.o: src/platform/headerOnly.cpp.o
.PHONY : src/platform/headerOnly.o

# target to build an object file
src/platform/headerOnly.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygame.dir/build.make CMakeFiles/mygame.dir/src/platform/headerOnly.cpp.o
.PHONY : src/platform/headerOnly.cpp.o

src/platform/headerOnly.i: src/platform/headerOnly.cpp.i
.PHONY : src/platform/headerOnly.i

# target to preprocess a source file
src/platform/headerOnly.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygame.dir/build.make CMakeFiles/mygame.dir/src/platform/headerOnly.cpp.i
.PHONY : src/platform/headerOnly.cpp.i

src/platform/headerOnly.s: src/platform/headerOnly.cpp.s
.PHONY : src/platform/headerOnly.s

# target to generate assembly for a file
src/platform/headerOnly.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygame.dir/build.make CMakeFiles/mygame.dir/src/platform/headerOnly.cpp.s
.PHONY : src/platform/headerOnly.cpp.s

src/platform/opterPlatformFunctions.o: src/platform/opterPlatformFunctions.cpp.o
.PHONY : src/platform/opterPlatformFunctions.o

# target to build an object file
src/platform/opterPlatformFunctions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygame.dir/build.make CMakeFiles/mygame.dir/src/platform/opterPlatformFunctions.cpp.o
.PHONY : src/platform/opterPlatformFunctions.cpp.o

src/platform/opterPlatformFunctions.i: src/platform/opterPlatformFunctions.cpp.i
.PHONY : src/platform/opterPlatformFunctions.i

# target to preprocess a source file
src/platform/opterPlatformFunctions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygame.dir/build.make CMakeFiles/mygame.dir/src/platform/opterPlatformFunctions.cpp.i
.PHONY : src/platform/opterPlatformFunctions.cpp.i

src/platform/opterPlatformFunctions.s: src/platform/opterPlatformFunctions.cpp.s
.PHONY : src/platform/opterPlatformFunctions.s

# target to generate assembly for a file
src/platform/opterPlatformFunctions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygame.dir/build.make CMakeFiles/mygame.dir/src/platform/opterPlatformFunctions.cpp.s
.PHONY : src/platform/opterPlatformFunctions.cpp.s

src/platform/platformInput.o: src/platform/platformInput.cpp.o
.PHONY : src/platform/platformInput.o

# target to build an object file
src/platform/platformInput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygame.dir/build.make CMakeFiles/mygame.dir/src/platform/platformInput.cpp.o
.PHONY : src/platform/platformInput.cpp.o

src/platform/platformInput.i: src/platform/platformInput.cpp.i
.PHONY : src/platform/platformInput.i

# target to preprocess a source file
src/platform/platformInput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygame.dir/build.make CMakeFiles/mygame.dir/src/platform/platformInput.cpp.i
.PHONY : src/platform/platformInput.cpp.i

src/platform/platformInput.s: src/platform/platformInput.cpp.s
.PHONY : src/platform/platformInput.s

# target to generate assembly for a file
src/platform/platformInput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygame.dir/build.make CMakeFiles/mygame.dir/src/platform/platformInput.cpp.s
.PHONY : src/platform/platformInput.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gl2d"
	@echo "... glad"
	@echo "... glfw"
	@echo "... glui"
	@echo "... imgui"
	@echo "... mygame"
	@echo "... raudio"
	@echo "... safeSave"
	@echo "... stb_image"
	@echo "... stb_truetype"
	@echo "... src/gameLayer/gameLayer.o"
	@echo "... src/gameLayer/gameLayer.i"
	@echo "... src/gameLayer/gameLayer.s"
	@echo "... src/platform/glfwMain.o"
	@echo "... src/platform/glfwMain.i"
	@echo "... src/platform/glfwMain.s"
	@echo "... src/platform/headerOnly.o"
	@echo "... src/platform/headerOnly.i"
	@echo "... src/platform/headerOnly.s"
	@echo "... src/platform/opterPlatformFunctions.o"
	@echo "... src/platform/opterPlatformFunctions.i"
	@echo "... src/platform/opterPlatformFunctions.s"
	@echo "... src/platform/platformInput.o"
	@echo "... src/platform/platformInput.i"
	@echo "... src/platform/platformInput.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/nncv/Projects/cmakeSetup/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

